### ISSUE TITLE
Portfolio review 

### ISSUE THREAD

**Issue by opeolluwa** [DeeDee932/My-Portfolio#1]
Hi there👋
I was checking through you portfolio. I'd like to offer a few pointers if I may. 

1. Date of birth is really necessary
2. You can use [emailjs](www.emailjs.com) yo handle your contact form. You can reach out if you need assistance ☺️
Happy Coding 💪🤓

**Comment by DeeDee932** [comment]
Hi Adeoye. Thanks for the review. I'd love to connect to work on the
portfolio and more projects. Would that be possible?

**Comment by opeolluwa** [comment]
Sure! you can reach out via adefemiadeoye@yahoo.com
